# Generated by Django 2.2.2 on 2023-10-09 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0003_auto_20231004_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(choices=[('PHILIPS', 'PHILIPS'), ('PUMA', 'PUMA'), ('ELICA', 'ELICA'), ('SUGAR', 'SUGAR'), ('AMAZON BOOKS', 'AMAZON BOOKS')], max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('ELECTRONICS', 'ELECTRONICS'), ('CLOTHING', 'CLOTHING'), ('KITCHEN APPLIANCES', 'KITCHEN APPLIANCES'), ('BEAUTY PRODUCTS', 'BEAUTY PRODUCTS'), ('BOOKS', 'BOOKS')], max_length=50),
        ),
    ]
